services:
  - type: web
    name: farm-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --force-reinstall --no-cache-dir -r requirements.txt
    startCommand: python bot.py
